# Generated by Django 4.2.8 on 2026-01-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='price',
            new_name='prices_ticker_961316_idx',
            old_name='prices_ticker_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='price',
            new_name='prices_ticker_415578_idx',
            old_name='prices_ticker__timestamp_idx',
        ),
    ]
